### ISSUE TITLE
Deep learning repo organization

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_extras#4]
How should we arrange the deep learning repo? (i was going to do some deep learning stuff, but can’t install/import nengo_lasagne cuz it’s not set up correctly atm).

The options seem to be that we can either split it into two (or more?) or keep it all together.  

I kinda like the idea of having nengo_deeplearning being the thing we use to stick deep nets in nengo (i.e. lasagne).  I'd be fine if the other methods stay there as well.  The other methods in there now include hessian free code from dan, and eric's supporting functions for things like convolution, etc.

**Comment by tbekolay** [comment]
There's a few decisions; I think the first is whether to split `nengo_lasagne` into a separate repo, then whether it's one or two repos, what those repos should be called.

I'm sort of inclined to split them into two because

1. `nengo_lasagne` depends on Theano which is hard to install, so we should avoid installing it if people just want to use some of the other things in this repo, and
2. this repo feels more like an experimental sandbox, where `nengo_lasagne` has "graduated" to a full-fledged operational project that should have its own set of docs and tests and PyPI entry, etc

I don't see many people using much of the stuff in this repo aside from the `nengo_lasagne` part, so having it separate makes the maintenance burden a bit smaller. If it's separate, I'd be fine with `nengo_deeplearning` or `nengo_lasagne`, though I think `nengo_lasagne` is more clear...

**Comment by celiasmith** [comment]
I think nengo_lasagne is more clear for people who know what lasagne is. 
But I suspect many nengo users won't, so then nengo_deeplearning would 
be better. I mean the docs and everything are clear about the lasagne 
relationship, of course. As for what the other repo would then be 
called, I'm not sure... 
nengo_extra_deep_learning_stuff_that_we_don't_know_where_to_put? Just 
throwing it out there.

Trevor Bekolay wrote:

**Comment by tbekolay** [comment]
`nengo_deeplearning_extras` or we could maintain a general repo for experimental features not quite ready for primetime in `nengo_experimental` or `nengo_sandbox` or something

**Comment by drasmuss** [comment]
It might be good to have a `nengo_sandbox` or `nengo_tools` type thing, I think there's a couple other projects in a similar vein that are scattered about in personal repos right now.

**Comment by hunse** [comment]
We can also have modules within a repository that aren't imported by default. For example, we could have a `lasagne` module in `nengo_deeplearning`, so that Theano isn't a requirement to use the other stuff. Or we could have a `sandbox` module in `nengo_deeplearning` for experimental stuff; this is what Theano does.

**Comment by celiasmith** [comment]
yeah aaron has some nengo tools as well... sandbox stuff.

**Comment by tbekolay** [comment]
I'd rather a separate repo for sandbox stuff so that it can be a true free-for-all and not get mixed up with repos that have more rules for branches and other systems in place.

So, one proposal would be: rename this repo to `nengo_experimental` and make a new `nengo_deeplearning` for the `nengo_lasagne` stuff. Thoughts?

**Comment by celiasmith** [comment]
+1

**Comment by hunse** [comment]
To me, this repo isn't all sandbox stuff though. My convnet stuff is good to go IMO, and the SoftLIF stuff is pretty much ready too. That's not to say they can't live here, but I guess I'm just wondering what the plan is for graduation? Where does the stuff here go when it's "ready"? Or does it just stay here, in which case this would be more `nengo_extra`? Will a `nengo_experimental` repo be something that users will look at? If we want to feature examples of using the things in this repo, where should they go so that people will see them?

**Comment by hunse** [comment]
Maybe just calling this `nengo_extra`, with the qualifier that some things here are not fully tested, will assuage my concerns. Even in a "sandbox" repo, I would still think that anything that is fully untested should remain on a separate branch, and we only merge them into master once they're at least at the beta stage.

**Comment by tbekolay** [comment]
That's fair! I'm cool with `nengo_extra` as I agree, the PRs I opened here I wouldn't want in master even for a sandbox repo. In a sense, the issues / PRs could serve a similar purpose to the [modelling-ideas repo](https://github.com/ctn-waterloo/modelling_ideas). And yeah, as things make sense to move elsewhere (like nengo_lasagne) they can move.

**Comment by tbekolay** [comment]
Renamed to `nengo_extras`! The nengo_lasagne stuff is being separated out into `nengo_deeplearning`.

**Comment by hunse** [comment]
The name of the main folder should change, too.

**Comment by hunse** [comment]
And the README needs an update to better reflect what we want to put in here (though I don't know what that is...)

**Comment by tbekolay** [comment]
Right, I'll make a PR updating this repo organization shortly.
